### ISSUE TITLE
Failure in generating error from an example netlist

### ISSUE THREAD

**Issue by supertjhok** [ALIGN-analoglayout/ALIGN-pdk-sky130#6]
Trying to compile the SKY130 five_transistor_ota example results in the following error:

$ schematic2layout.py ../ALIGN-pdk-sky130/examples/five_transistor_ota -p ../ALIGN-pdk-sky130/SKY130_PDK/

align.main INFO : Reading netlist: /home/supertjhok/ALIGN-public/ALIGN-pdk-sky130/examples/five_transistor_ota/five_transistor_ota.sp subckt=FIVE_TRANSISTOR_OTA, flat=0
align.compiler.compiler INFO : Starting topology identification...
align.compiler.user_const INFO : Reading constraint file: [PosixPath('/home/supertjhok/ALIGN-public/ALIGN-pdk-sky130/examples/five_transistor_ota/five_transistor_ota.const.json')]
align.compiler.compiler INFO : Completed topology identification.
align.cmdline ERROR : Fatal Error. Cannot proceed
Traceback (most recent call last):
  File "/home/supertjhok/ALIGN-public/general/lib/python3.9/site-packages/align/cmdline.py", line 166, in parse_args
    return schematic2layout(**vars(arguments))
  File "/home/supertjhok/ALIGN-public/general/lib/python3.9/site-packages/align/main.py", line 176, in schematic2layout
    primitives = generate_primitives(primitive_lib, pdk_dir, primitive_dir, netlist_dir)
  File "/home/supertjhok/ALIGN-public/general/lib/python3.9/site-packages/align/primitive/main.py", line 149, in generate_primitives
    uc = generate_primitive(block_name, primitive_def,  ** block_args,
  File "/home/supertjhok/ALIGN-public/general/lib/python3.9/site-packages/align/primitive/main.py", line 179, in generate_primitive
    uc, _ = generate_MOS_primitive(pdkdir, block_name, primitive, height, value, x_cells, y_cells,
  File "/home/supertjhok/ALIGN-public/general/lib/python3.9/site-packages/align/primitive/main.py", line 44, in generate_MOS_primitive
    uc = generator(pdk, height, fin, gate, gateDummy, shared_diff, stack, bodyswitch, primitive_constraints=primitive.constraints)
TypeError: __init__() got an unexpected keyword argument 'primitive_constraints'

**Comment by arvuce22** [comment]
@supertjhok Try it now. It is working for me.

![image](https://user-images.githubusercontent.com/44516577/168386136-ce4dc236-2104-4c72-b59a-e1f390f3daa9.png)
