### ISSUE TITLE
Error in generating layout from example netlist

### ISSUE THREAD

**Issue by supertjhok** [ALIGN-analoglayout/ALIGN-pdk-sky130#7]
After updating to the latest version (as of 05/16/22), of both ALIGN-public and ALIGN-pdk-sky130, trying to generate the 5T OTA example still generates a Python error:

(general) supertjhok@ubuntu:~/ALIGN-public/work$ schematic2layout.py ../pdks/ALIGN-pdk-sky130/examples/five_transistor_ota -p ../pdks/ALIGN-pdk-sky130/SKY130_PDK/
align.main INFO : Reading netlist: /home/supertjhok/ALIGN-public/pdks/ALIGN-pdk-sky130/examples/five_transistor_ota/five_transistor_ota.sp subckt=FIVE_TRANSISTOR_OTA, flat=0
align.compiler.compiler INFO : Starting topology identification...
align.compiler.user_const INFO : Reading constraint file: [PosixPath('/home/supertjhok/ALIGN-public/pdks/ALIGN-pdk-sky130/examples/five_transistor_ota/five_transistor_ota.const.json')]
align.compiler.compiler INFO : Completed topology identification.
align.cmdline ERROR : Fatal Error. Cannot proceed
Traceback (most recent call last):
  File "/home/supertjhok/ALIGN-public/general/lib/python3.9/site-packages/align/cmdline.py", line 166, in parse_args
    return schematic2layout(**vars(arguments))
  File "/home/supertjhok/ALIGN-public/general/lib/python3.9/site-packages/align/main.py", line 176, in schematic2layout
    primitives = generate_primitives(primitive_lib, pdk_dir, primitive_dir, netlist_dir)
  File "/home/supertjhok/ALIGN-public/general/lib/python3.9/site-packages/align/primitive/main.py", line 149, in generate_primitives
    uc = generate_primitive(block_name, primitive_def,  ** block_args,
  File "/home/supertjhok/ALIGN-public/general/lib/python3.9/site-packages/align/primitive/main.py", line 179, in generate_primitive
    uc, _ = generate_MOS_primitive(pdkdir, block_name, primitive, height, value, x_cells, y_cells,
  File "/home/supertjhok/ALIGN-public/general/lib/python3.9/site-packages/align/primitive/main.py", line 80, in generate_MOS_primitive
    return uc, gen(pattern, connections)
  File "/home/supertjhok/ALIGN-public/general/lib/python3.9/site-packages/align/primitive/main.py", line 68, in gen
    uc.addNMOSArray(x_cells, y_cells, pattern, vt_type, routing, **parameters)
  File "/home/supertjhok/ALIGN-public/pdks/ALIGN-pdk-sky130/SKY130_PDK/mos.py", line 293, in addNMOSArray
    self._addMOSArray(x_cells, y_cells, pattern, vt_type, connections, **parameters)
  File "/home/supertjhok/ALIGN-public/pdks/ALIGN-pdk-sky130/SKY130_PDK/mos.py", line 256, in _addMOSArray
    self._nets = collections.defaultdict(lambda: collections.defaultdict(list)) # net:m2track:m1contacts (Updated by self._connectDevicePins)
NameError: name 'collections' is not defined

Test system: Ubuntu 21.10; Python version 3.9.7

**Comment by supertjhok** [comment]
Problem solved by cleaning up the work directory (e.g., deleting files from earlier runs) before trying the compilation. Thanks.
