### ISSUE TITLE
AssertionError: **Model SKY130_FD_PR__NFET_01V8 has 4 pins ['D', 'G', 'S', 'B']**. 

### ISSUE THREAD

**Issue by kunalg123** [ALIGN-analoglayout/ALIGN-pdk-sky130#8]
I am trying below basic charge pump circuit which works 

.subckt charge_pump up down out
M43 net3 net2 vdd vdd sky130_fd_pr__pfet_01v8 l=150n w=18u
M44 out downb net3 vdd sky130_fd_pr__pfet_01v8 l=150n w=420n  
M31 out up net7 vss sky130_fd_pr__nfet_01v8 l=150n w=420n
M32 net7 net8 vss vss sky130_fd_pr__nfet_01v8 l=150n w=4.8u

M33 net2 net2 vdd vdd sky130_fd_pr__pfet_01v8 l=150n w=420n 
M34 net8 net8 vss vss sky130_fd_pr__nfet_01v8 l=150n w=420n

M35 net9 down net3 vdd sky130_fd_pr__pfet_01v8 l=150n w=5400n
M36 net9 net9 vss vss sky130_fd_pr__nfet_01v8 l=150n w=420n

M37 net10 net10 vdd vdd sky130_fd_pr__pfet_01v8 l=150n w=420n
M38 net10 upb net7 vss sky130_fd_pr__nfet_01v8 l=150n w=5400n

M39 vdd down downb vdd sky130_fd_pr__pfet_01v8 l=150n w=720n
M40 vss down downb vss sky130_fd_pr__nfet_01v8 l=150n w=360n 

M41 vdd up upb vdd sky130_fd_pr__pfet_01v8 l=150n w=720n 
M42 vss up upb vss sky130_fd_pr__nfet_01v8 l=150n w=360n 

.ends charge_pump

It gives an below assertion error, even though I am passing 4 pins as per spice deck standard specs. Am i missing anything?

align.cmdline ERROR : Fatal Error. Cannot proceed
Traceback (most recent call last):
  File "/home/kunalg/ALIGN-public/general/lib/python3.8/site-packages/align/cmdline.py", line 166, in parse_args
    return schematic2layout(**vars(arguments))
  File "/home/kunalg/ALIGN-public/general/lib/python3.8/site-packages/align/main.py", line 163, in schematic2layout
    primitive_lib = generate_hierarchy(netlist, subckt, topology_dir, flatten, pdk_dir)
  File "/home/kunalg/ALIGN-public/general/lib/python3.8/site-packages/align/compiler/compiler.py", line 27, in generate_hierarchy
    ckt_data, primitive_library = compiler_input(
  File "/home/kunalg/ALIGN-public/general/lib/python3.8/site-packages/align/compiler/compiler.py", line 76, in compiler_input
    ckt_parser.parse(lines)
  File "/home/kunalg/ALIGN-public/general/lib/python3.8/site-packages/align/schema/parser.py", line 88, in parse
    self._dispatch(cache)
  File "/home/kunalg/ALIGN-public/general/lib/python3.8/site-packages/align/schema/parser.py", line 106, in _dispatch
    self._process_instance(token.value.upper(), args, kwargs)
  File "/home/kunalg/ALIGN-public/general/lib/python3.8/site-packages/align/schema/parser.py", line 161, in _process_instance
    assert len(args) == len(model.pins), \
AssertionError: **Model SKY130_FD_PR__NFET_01V8 has 4 pins ['D', 'G', 'S', 'B']**. 16 nets ['NET3', 'NET2', 'VDD', 'VDD', 'SKY130_FD_PR__PFET_01V8', 'M44', 'OUT', 'DOWNB', 'NET3', 'VDD', 'SKY130_FD_PR__PFET_01V8', 'M31', 'OUT', 'UP', 'NET7', 'VSS'] were passed when instantiating M43.

attaching spice file and json file here
[charge_pump.zip](https://github.com/ALIGN-analoglayout/ALIGN-pdk-sky130/files/9475041/charge_pump.zip)

**Comment by ChrisZonghaoLi** [comment]
I am not sure if you were using any schematic entry to generate the netlist (which I recommend xschem) or if you were just doing so by hand. From my experience the transistor SPICE model in this technology was written in the fashion of using subckt as the wrapper for those transistors (meaning that you cannot directly instantiate your transistor with `M`, but should using subckt `X`. Dig the SPICE code inside `libs.tech` and you will see why (sorry I do not have the access to my remote working station now so I just pull these up from my memory).
